package com.pawwork.android.docs

import java.io.ByteArrayOutputStream
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

object DocGenerator {

    fun generateDocx(dir: File): File {
        val name = "report_${ts()}.docx"
        val file = File(dir, name)
        ZipOutputStream(FileOutputStream(file)).use { zip ->
            zip.putEntry("[Content_Types].xml", """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
                    <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
                    <Default Extension="xml" ContentType="application/xml"/>
                    <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
                </Types>""".trimIndent())
            zip.putEntry("_rels/.rels", """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
                    <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
                </Relationships>""".trimIndent())
            zip.putEntry("word/_rels/document.xml.rels", """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>""".trimIndent())
            zip.putEntry("word/document.xml", """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
                <w:body>
                    <w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t>PawWork Office Document</w:t></w:r></w:p>
                    <w:p><w:r><w:rPr><w:b/></w:rPr><w:t>This is a professionally formatted Word document</w:t></w:r></w:p>
                    <w:p><w:r><w:t>generated by PawWork for Android, reusing the office-docx skill concept</w:t></w:r></w:p>
                    <w:p><w:r><w:t>from the PawWork desktop app (vinothus/pawwork-linux).</w:t></w:r></w:p>
                    <w:p><w:pPr><w:pStyle w:val="Heading2"/></w:pPr><w:r><w:t>Features</w:t></w:r></w:p>
                    <w:p><w:r><w:t>• Real Heading styles (drives navigation pane &amp; TOC)</w:t></w:r></w:p>
                    <w:p><w:r><w:t>• Native Word tables with headers</w:t></w:r></w:p>
                    <w:p><w:r><w:t>• Explicit fonts and formatting</w:t></w:r></w:p>
                    <w:p><w:pPr><w:pStyle w:val="Heading2"/></w:pPr><w:r><w:t>Generated</w:t></w:r></w:p>
                    <w:p><w:r><w:t>${SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.US).format(Date())}</w:t></w:r></w:p>
                </w:body></w:document>""".trimIndent())
        }
        return file
    }

    fun generateXlsx(dir: File): File {
        val name = "spreadsheet_${ts()}.xlsx"
        val file = File(dir, name)
        ZipOutputStream(FileOutputStream(file)).use { zip ->
            zip.putEntry("[Content_Types].xml", """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
                    <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
                    <Default Extension="xml" ContentType="application/xml"/>
                    <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
                    <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
                    <Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/>
                </Types>""".trimIndent())
            zip.putEntry("_rels/.rels", """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
                    <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
                </Relationships>""".trimIndent())
            zip.putEntry("xl/_rels/workbook.xml.rels", """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
                    <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
                    <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/>
                </Relationships>""".trimIndent())
            zip.putEntry("xl/workbook.xml", """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
                    <sheets><sheet name="PawWork Data" sheetId="1" r:id="rId1" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"/></sheets>
                </workbook>""".trimIndent())
            zip.putEntry("xl/sharedStrings.xml", """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="12" uniqueCount="12">
                    <si><t>Task</t></si><si><t>Status</t></si><si><t>Priority</t></si>
                    <si><t>Write Chat UI</t></si><si><t>Done</t></si><si><t>High</t></si>
                    <si><t>Office Docs</t></si><si><t>In Progress</t></si><si><t>High</t></si>
                    <si><t>Web Search</t></si><si><t>Planned</t></si><si><t>Medium</t></si>
                </sst>""".trimIndent())
            zip.putEntry("xl/worksheets/sheet1.xml", """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
                    <sheetData>
                        <row r="1"><c r="A1" t="s"><v>0</v></c><c r="B1" t="s"><v>1</v></c><c r="C1" t="s"><v>2</v></c></row>
                        <row r="2"><c r="A2" t="s"><v>3</v></c><c r="B2" t="s"><v>4</v></c><c r="C2" t="s"><v>5</v></c></row>
                        <row r="3"><c r="A3" t="s"><v>6</v></c><c r="B3" t="s"><v>7</v></c><c r="C3" t="s"><v>8</v></c></row>
                        <row r="4"><c r="A4" t="s"><v>9</v></c><c r="B4" t="s"><v>10</v></c><c r="C4" t="s"><v>11</v></c></row>
                    </sheetData>
                </worksheet>""".trimIndent())
        }
        return file
    }

    fun generatePptx(dir: File): File {
        val name = "presentation_${ts()}.pptx"
        val file = File(dir, name)
        ZipOutputStream(FileOutputStream(file)).use { zip ->
            zip.putEntry("[Content_Types].xml", """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
                    <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
                    <Default Extension="xml" ContentType="application/xml"/>
                    <Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>
                    <Override PartName="/ppt/slides/slide1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>
                </Types>""".trimIndent())
            zip.putEntry("_rels/.rels", """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
                    <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
                </Relationships>""".trimIndent())
            zip.putEntry("ppt/_rels/presentation.xml.rels", """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
                    <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide1.xml"/>
                </Relationships>""".trimIndent())
            zip.putEntry("ppt/presentation.xml", """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
                    <p:sldIdLst><p:sldId id="256" r:id="rId1" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"/></p:sldIdLst>
                    <p:sldSz cx="9144000" cy="6858000" type="screen4x3"/>
                </p:presentation>""".trimIndent())
            zip.putEntry("ppt/slides/slide1.xml", """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
                    <p:cSld><p:spTree>
                        <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
                        <p:grpSpPr/>
                        <p:sp><p:nvSpPr><p:cNvPr id="2" name="title"/><p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr><p:nvPr><p:ph type="title"/></p:nvPr></p:nvSpPr>
                            <p:spPr><a:xfrm><a:off x="457200" y="274638"/><a:ext cx="8229600" cy="1143000"/></a:xfrm></p:spPr>
                            <p:txBody><a:p><a:r><a:rPr lang="en-US" sz="3200" b="1"/><a:t>PawWork for Android</a:t></a:r></a:p></p:txBody>
                        </p:sp>
                        <p:sp><p:nvSpPr><p:cNvPr id="3" name="body"/><p:cNvSpPr/><p:nvPr><p:ph idx="1"/></p:nvPr></p:nvSpPr>
                            <p:spPr><a:xfrm><a:off x="457200" y="1571625"/><a:ext cx="8229600" cy="4525963"/></a:xfrm></p:spPr>
                            <p:txBody><a:p><a:r><a:rPr lang="en-US" sz="1800"/><a:t>🐾 AI-powered document agent for Android</a:t></a:r></a:p>
                                <a:p><a:r><a:rPr lang="en-US" sz="1800"/><a:t>• Chat with AI providers (DeepSeek, OpenAI, Ollama)</a:t></a:r></a:p>
                                <a:p><a:r><a:rPr lang="en-US" sz="1800"/><a:t>• Generate Word, Excel, PowerPoint, PDF</a:t></a:r></a:p>
                                <a:p><a:r><a:rPr lang="en-US" sz="1800"/><a:t>• Web search and file management</a:t></a:r></a:p>
                                <a:p><a:r><a:rPr lang="en-US" sz="1800"/><a:t>• Task automations</a:t></a:r></a:p></p:txBody>
                        </p:sp>
                    </p:spTree></p:cSld>
                </p:sld>""".trimIndent())
        }
        return file
    }

    fun generatePdf(dir: File): File {
        val name = "document_${ts()}.pdf"
        val file = File(dir, name)
        val now = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.US).format(Date())
        file.writeText("""
            %PDF-1.4
            1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
            2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
            3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Resources<</Font<</F1 4 0 R>>>>/Contents 5 0 R>>endobj
            4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj
            5 0 obj
            <</Length 434>>
            stream
            BT
            /F1 24 Tf 50 720 Td (PawWork PDF Document) Tj
            /F1 12 Tf 50 680 Td (Generated by PawWork for Android) Tj
            /F1 12 Tf 50 660 Td (Reuses the office-pdf skill concept from pawwork-linux) Tj
            /F1 12 Tf 50 630 Td (Features: Real headings, formatted text, native layout) Tj
            /F1 10 Tf 50 590 Td (Date: $now) Tj
            ET
            endstream
            endobj
            xref
            0 6
            0000000000 65535 f 
            0000000009 00000 n 
            0000000058 00000 n 
            0000000115 00000 n 
            0000000266 00000 n 
            0000000340 00000 n 
            trailer<</Size 6/Root 1 0 R>>
            startxref
            826
            %%EOF
        """.trimIndent().trimIndent())
        return file
    }

    private fun ZipOutputStream.putEntry(name: String, content: String) {
        putNextEntry(ZipEntry(name))
        write(content.toByteArray(Charsets.UTF_8))
        closeEntry()
    }

    private fun ts() = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date())
}